### ISSUE TITLE
[🛠️Fix] リンタ―の導入に伴うコードの修正

### ISSUE THREAD

**Issue by snow7y** [KTC-Security-Circle/SC-system-backend#33]
## 改善したい機能
リンタ―の導入に伴う

## 具体的な改善案
RuffとMypyのエラーがなくなるようにコードを修正する

## 現状の問題点
今のコードより、Pythonらしいコードを書ける環境にする

## 追加情報
特になし

## TODO
- [ ] Ruffのエラーをなくす
- [ ] Mypyのエラーをなくす
- [ ] 問題なくコードが動くか確認する

**Comment by Shieru-ktc** [comment]
試しに一個書いてみましたけどこんな感じでいいですか？
0b5ac58f7d4e4a484a0f146db677f615267bd0c8
